Add config contexts to Router and RoutingPolicy
peering-manager/peering-manager pull request #417
Opened 2021-05-12 21:39 UTC by ggidofalvy-tc

### Adds a feature based on the following PRs:
- https://github.com/peering-manager/peering-manager/issues/287
- https://github.com/peering-manager/peering-manager/issues/97

This proposed change adds a very similar concept to the config contexts we know and love to routing policies and routers. A relatively small change, but it unlocks many new possibilities for those who use Peering Manager as a source of truth for their BGP peering config.

2021-05-12 21:55 UTC, jamesditrapani requested changes
Could you please update the Model Documentation in `docs/model/peering`, perhaps adding some examples too would be good!

2021-05-12 23:12 UTC, ggidofalvy-tc commented
I have added some additional docs.

2021-05-13 09:53 UTC, gmazoyer commented
A couple of question/remarks:

1. Should we also provide Jinja2 filters to access/manipulate config contexts?
2. It would be great to also be able to display config contexts as YAML (as it's commonly used). The database field would still be a JSON field though. Adding a couple of buttons to switch from JSON to YAML and vice versa in the user interface would be enough.

2021-05-13 10:07 UTC, gmazoyer commented on docs/models/peering/router.md
> +    context for e.g. tooling that accesses Peering-Manager programmatically.
`Peering-Manager` -> `Peering Manager`

2021-05-13 10:07 UTC, gmazoyer commented on docs/models/peering/routingpolicy.md
> +    context for e.g. tooling that accesses Peering-Manager programmatically.
`Peering-Manager` → `Peering Manager`

2021-05-13 10:12 UTC, gmazoyer requested changes
Solid PR addressing issues as mentioned. Some details to fix, but can be merged as soon as they are fixed.

2021-05-13 10:12 UTC, gmazoyer commented on peering/forms.py
> +    config_context = JSONField(required=False, label="Context", widget=SmallTextarea)
Maybe using `Config context` as label instead of just `Context` for better understanding.

2021-05-13 10:12 UTC, gmazoyer commented on peering/forms.py
> +    config_context = JSONField(required=False, label="Context", widget=SmallTextarea)
Maybe using `Config context` as label instead of just `Context` for better understanding.

2021-05-13 10:12 UTC, gmazoyer commented on docs/models/peering/router.md
> +    context for e.g. tooling that accesses Peering-Manager programmatically.
`Peering-Manager` → `Peering Manager`

2021-05-13 10:12 UTC, gmazoyer commented on docs/models/peering/routingpolicy.md
> +    context for e.g. tooling that accesses Peering-Manager programmatically.
`Peering-Manager` → `Peering Manager`

2021-05-15 16:52 UTC, gmazoyer approved these changes
LGTM - using YAML format as well can be implemented later

2021-05-17 07:42 UTC, ggidofalvy-tc commented
Thanks for pushing those fixes @gmazoyer, had a long weekend off and just arrived back to this PR. :)

2021-05-17 10:13 UTC, jamesditrapani approved these changes
Looks good, thanks for your contribution!

2021-05-17 10:27 UTC, merged