Direct connection: Interface and VLAN options
peering-manager/peering-manager pull request #485
Opened 2021-09-20 13:37 UTC by lukas2511

### Fixes:

* [x]  Add Interface option to direct connections
* [x]  Add VLAN option to direct connections

2021-09-20 13:53 UTC, jamesditrapani requested changes
Looks like black & isort pre merge checks have failed. Can you please run black & isort to ensure the new code is within specification. Thank you for your contribution!

2021-09-20 13:53 UTC, jamesditrapani commented on peering/migrations/0079_directpeeringsession_vlan.py
> +class Migration(migrations.Migration):
Let's squash both migration files into one.

2021-09-20 13:53 UTC, jamesditrapani commented on peering/models/models.py
> +    interface = models.CharField(max_length=200, blank=True)
You will need to update the test cases in peering/tests with the new fields 😀

2021-09-20 15:03 UTC, lukas2511 commented
I merged the db migration and added the fields to the tests. isort and black are also looking good on my end, hopefully CI thinks the same :D

2021-09-21 10:15 UTC, jamesditrapani requested changes

2021-09-21 10:15 UTC, jamesditrapani commented on peering/models/models.py
> +    interface = models.CharField(max_length=200, blank=True)
The only other thing that I would point out is to ensure the documentation is updated for the DirectPeeringSession model here https://github.com/peering-manager/peering-manager/blob/435f75e87cbb49941e10c7bd5a4663ae398867bc/docs/models/peering/directpeeringsession.md

Sorry, forgot to include this in the previous review! :)

2021-09-26 16:42 UTC, gmazoyer commented
I'd advise to use the `net.models.Connection` class instead of duplicating fields specifically for direct peering session. The `Connection` model was introduced to do just this.

2021-11-21 23:22 UTC, jamesditrapani commented
Hi @lukas2511, did you want to have a look at moving this to use `net.models.Connection` as @gmazoyer suggested? If not I can jump into your branch and do so :)

2021-11-21 23:41 UTC, lukas2511 commented
> Hi @lukas2511, did you want to have a look at moving this to use `net.models.Connection` as @gmazoyer suggested? If not I can jump into your branch and do so :)

Unfortunately I didn't find time to look into this. My simple solution was working fine for me and I didn't really want to invest any more work.

2022-02-21 04:20 UTC, closed without merging