Option to select a custom configuration when doing config deployment
peering-manager/peering-manager pull request #817
Opened 2024-02-08 09:07 UTC by rinsekloek

* Option to select alternative Configuration 

Added an extra parameter when doing 'configure_routers' from the CLI. This extra parameyer gives you the option to select a specific template to be deployed. For example to update prefix-lists from IRR updates during a daily cron and not deploy the complete configuration template:

```
usage: manage.py configure_routers [-h] [--no-commit-check] [--limit [LIMIT]] [-t] [-c CONFIG] [--version] [-v {0,1,2,3}] [--settings SETTINGS] [--pythonpath PYTHONPATH]
                                   [--traceback] [--no-color] [--force-color] [--skip-checks]

Deploy configurations on routers.

optional arguments:
...
  -c CONFIG, --config CONFIG
                        Override default configuration to use for config generation/deployment. Give the name of the configuration.
...
```

* Example:

```
# python3 /opt/peering-manager/manage.py configure_routers -c "Nokia SROS Prefix lists update" --limit sros01
[*] Selecting configuration template 'Nokia SROS Prefix lists update'
[*] Deploying configurations
  - sros01 ... success
```

2024-02-08 20:37 UTC, gmazoyer requested changes
Check comment for minor change. The documentation related to the Nokia SROS template might be better in another PR dedicated to it. The PR looks good.

2024-02-08 20:37 UTC, gmazoyer commented on peering/management/commands/configure_routers.py
> +        config_override=False,
If `config_override` is supposed to be a string containing the name of the config, the default value would probably better as `""` or `None`.

2024-02-09 07:02 UTC, rinsekloek commented
I have changed the default to "" and removed the nokia-sros from the main branch. (My inted was that it was not included in this PR)

2024-02-09 10:22 UTC, gmazoyer approved these changes
LGTM

2024-02-09 21:42 UTC, merged

2024-08-23 10:16 UTC, rinsekloek commented
> Check comment for minor change. The documentation related to the Nokia SROS template might be better in another PR dedicated to it. The PR looks good.

I have started with the Nokia SROS template in a seperate branch:
https://github.com/rinsekloek/peering-manager/blob/nokia-sros/docs/templating/examples/nokia-sros.md